services:
  harvester:
    build:
      context: .
      dockerfile: Dockerfile.harvester
    environment:
      HARVEST_ENDPOINT_URL: ${HARVEST_ENDPOINT_URL}
      HARVEST_API_KEY: ${HARVEST_API_KEY}
      X_BEARER_TOKEN: ${X_BEARER_TOKEN}
    restart: "no"
